---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
keywords:
  - graph
  - open
  - close
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GD-Graph-ohlc
no_index:
  directory:
    - t
    - inc
requires:
  GD::Graph: 0
  perl: 5.006001
resources:
  repository: http://github.com/jettero/gd--graph--ohlc/
version: 0.9606
